### ISSUE TITLE
after update 2.2.2 it just crashes on start up

### ISSUE THREAD

**Issue by aminenr-hub** [saVantCZ/PS5reborn#32] opened 2024-12-12 18:04 UTC
as the title says

**Comment by saVantCZ** [comment] 2024-12-12 18:19
Upload playnite.log file right after crash

**Comment by aminenr-hub** [comment] 2024-12-12 18:27
where can i find it also just downgraded to 2.1 and its working fine

**Comment by aminenr-hub** [comment] 2024-12-12 18:31
[playnite.log](https://github.com/user-attachments/files/18115989/playnite.log)
here is the log file

**Comment by saVantCZ** [comment] 2024-12-12 18:56
looks like you are trying to load whole library of games at once, like hundreds or thousands of games at once and runs out of memory. 

Its reccomended to create filter presets to limit number of games shown at once

**Comment by aminenr-hub** [comment] 2024-12-12 19:02
![image](https://github.com/user-attachments/assets/092bc0b2-0b00-4cca-886a-edbd9a1f285e)
here is everything i have i dont have hundreds of games

**Comment by saVantCZ** [comment] 2024-12-12 19:19
No idea then, new version did nothing that breaking, only added themes. You can also send me extensions.log file after crash if it help.

**Comment by aminenr-hub** [comment] 2024-12-12 19:24
ALL KEEP USING 2.1 UNTIL I FIGURE OUT WHY IT CRASH ON NEWER VER OR DO A CLEAN INSTALL OF PLAYNITE AND THE THEME 
[extensions.log](https://github.com/user-attachments/files/18116518/extensions.log)

**Comment by saVantCZ** [comment] 2024-12-13 15:00
Let me know if anything fixes it, because noone other reported crashing, extension log is just cut at end due crash i guess.

**Comment by aminenr-hub** [comment] 2024-12-14 22:08
yeah sure if i ever found the reason why it crashing ill post it here

**Comment by foss-lover34** [comment] 2024-12-15 00:16
try to reset your whole playnite, everything works for me which is surprising

**Comment by foss-lover34** [comment] 2024-12-15 00:17
> looks like you are trying to load whole library of games at once, like hundreds or thousands of games at once and runs out of memory.
> 
> Its reccomended to create filter presets to limit number of games shown at once

this doesnt seem to be the reason in this parcticular case because this dude has few games but is it true that if there are too much playnite might just crash and not work like you said here?

**Comment by MoeinLM** [comment] 2024-12-16 09:30
I think the problem is high quality intro video because I've had the same problem since 4k intro video was added.
I turned 4k intro off in the settings but nothing changed.

**Comment by saVantCZ** [comment] 2024-12-16 09:38
Try removing 4k video file from theme folder

**Comment by aminenr-hub** [comment] 2024-12-16 21:51
![Uploading Screenshot 2024-12-16 224900.png…]()
thanks now its working tho , the older ver works with the 4k intro fine

**Comment by aminenr-hub** [comment] 2024-12-16 22:03
thanks now its working , tho the older ver works with the 4k intro fine
![Screenshot 2024-12-16 224900](https://github.com/user-attachments/assets/c9b31cf0-c9e5-435f-8328-19e9ef512300)

**Comment by saVantCZ** [comment] 2024-12-23 15:47
Should be fixed in 2.3.0

**Closed by saVantCZ** 2024-12-23 15:47 UTC

**Comment by aminenr-hub** [comment] 2024-12-23 17:16
yeah after the update its fixed now . thanks
